# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      

      - name: Install reticulate
        run: |
          Rscript -e "install.packages('reticulate')"
      
      - name: Create miniconda
        run: |
          Rscript -e "reticulate::install_miniconda()"
          Rscript -e "reticulate::conda_install(packages = 'scipy')"
          
      - name: Install pak
        run: |
          Rscript -e "install.packages('pak')"
          
      - name: Install GiottoUtils
        run: |
          Rscript -e "pak::pkg_install('drieslab/GiottoUtils')"
      
      - name: Install GiottoData
        run: |
          Rscript -e "pak::pkg_install('drieslab/GiottoData')"
          
      - name: Install rcmdcheck
        run: |
          Rscript -e "install.packages('rcmdcheck')"
      
      - name: Install knitr
        run: |
          Rscript -e "install.packages('knitr')"
      
      - name: Install rmarkdown
        run: |
          Rscript -e "install.packages('rmarkdown')"
      
      - name: Install testthat
        run: |
          Rscript -e "install.packages('testthat')"

      - name: Install BiocCheck
        run: |
          Rscript -e "install.packages('BiocManager')"
          Rscript -e "BiocManager::install('BiocCheck')"
      
      - name: Install dbscan
        run: |
          Rscript -e "BiocManager::install('dbscan')"
      
      - name: Install deldir
        run: |
          Rscript -e "BiocManager::install('deldir')"
      
      - name: Install igraph
        run: |
          Rscript -e "BiocManager::install('igraph')"
      
      - name: Install magick
        run: |
          Rscript -e "BiocManager::install('magick')"
      
      - name: Install matrixStats
        run: |
          Rscript -e "BiocManager::install('matrixStats')"
      
      - name: Install sp
        run: |
          Rscript -e "BiocManager::install('sp')"
      
      - name: Install terra
        run: |
          Rscript -e "BiocManager::install('terra')"
      
      - name: Install scattermore
        run: |
          Rscript -e "install.packages('scattermore')"
      
      - name: Install exactextractr
        run: |
          Rscript -e "install.packages('exactextractr')"
      
      - name: Install future.apply
        run: |
          Rscript -e "BiocManager::install('future.apply')"
          
      - name: Install stars
        run: |
          Rscript -e "BiocManager::install('stars')"
      
      - name: Install qs
        run: |
          Rscript -e "BiocManager::install('qs')"
      
      - name: Install RTriangle
        run: |
          Rscript -e "BiocManager::install('RTriangle')"
      
      - name: Install geometry
        run: |
          Rscript -e "BiocManager::install('geometry')"
      
      - name: Install Seurat
        run: |
          Rscript -e "BiocManager::install('Seurat')"

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          
      

      - name: Run BiocCheck
        run: |
          Rscript -e "BiocCheck::BiocCheck()"


